/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val rect = Rectangle(5.0, 10.0)
    rect.displayInfo()

    val sq = Square(5.0)
    sq.displayInfo()
}
