/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
 
    public static void main(String[] args) {
       System.out.println("Someone Car");
       Car someoneCar = new Car("Model S", "Tesla");
       someoneCar.setYear(2022);
       System.out.println("Car Make: " + someoneCar.getMake());
       System.out.println("Car Model: " + someoneCar.getModel());
       System.out.println("Car Year: " + someoneCar.getYear());
       //someoneCar.setIgnitionOn(true);
       someoneCar.move();
       //myCar.setIgnitionOn(false);  

        System.out.println("MY Car");

        Car myCar = new Car("Ioniq", "Hyundai");
        myCar.setYear(2025);
        System.out.println("Car Make: " + myCar.getMake());  
        myCar.setIgnitionOn(true);
        myCar.openTrunk();
        myCar.move();
        myCar.closeTrunk(); 

        System.out.println("Naveen Bike");
        Bike naveenBike = new Bike("350", "BMW");
       // naveenBike.move();
        naveenBike.kickStart();
        naveenBike.kickStart();
       // naveenBike.move();
    }
}
